verison : 3

services:
  client:
    build: client
    network_mode: host
    ports: 
       - '8080:8080'
  server:
    build: server
    network_mode: host
    environment:
      - PORT=3000
    ports:
      - '3000:3000'